// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d_conv2d,hls_ip_2024_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.840000,HLS_SYN_LAT=333989,HLS_SYN_TPT=none,HLS_SYN_MEM=37,HLS_SYN_DSP=0,HLS_SYN_FF=4537,HLS_SYN_LUT=5426,HLS_VERSION=2024_1}" *)

module conv2d (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in_image;
wire   [63:0] out_image;
reg    gmem1_blk_n_AW;
wire    ap_CS_fsm_state8;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state15;
reg   [63:0] out_image_read_reg_170;
reg   [63:0] in_image_read_reg_176;
wire   [15:0] max_val_fu_161_p3;
reg   [15:0] max_val_reg_193;
wire    ap_CS_fsm_state9;
reg   [13:0] out_image_x_address0;
reg    out_image_x_ce0;
reg    out_image_x_we0;
wire   [10:0] out_image_x_q0;
reg   [13:0] out_image_y_address0;
reg    out_image_y_ce0;
reg    out_image_y_we0;
wire   [10:0] out_image_y_q0;
reg   [13:0] out_image_sobel_address0;
reg    out_image_sobel_ce0;
reg    out_image_sobel_we0;
wire   [12:0] out_image_sobel_q0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_ready;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WVALID;
wire   [7:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WDATA;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WSTRB;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WLAST;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WID;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_RREADY;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_BREADY;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_ce0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_we0;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_d0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_ready;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WVALID;
wire   [7:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WDATA;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WSTRB;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WLAST;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WID;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_RREADY;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_BREADY;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_ce0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_we0;
wire   [10:0] grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_d0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_ready;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_ce0;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_ce0;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_ce0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_we0;
wire   [12:0] grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_d0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_ready;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_ce0;
wire   [15:0] grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out;
wire    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out_ap_vld;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_done;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_idle;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_ready;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WVALID;
wire   [7:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WDATA;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WSTRB;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WLAST;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WID;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARVALID;
wire   [63:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARADDR;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARID;
wire   [31:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARLEN;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARBURST;
wire   [1:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARPROT;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARQOS;
wire   [3:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARREGION;
wire   [0:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARUSER;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_RREADY;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_BREADY;
wire   [13:0] grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_address0;
wire    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_ce0;
wire    gmem_AWREADY;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [7:0] gmem_RDATA;
wire   [10:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem1_AWVALID;
wire    gmem1_AWREADY;
reg   [63:0] gmem1_AWADDR;
reg   [31:0] gmem1_AWLEN;
reg    gmem1_WVALID;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [7:0] gmem1_RDATA;
wire   [10:0] gmem1_RFIFONUM;
wire    gmem1_BVALID;
reg    gmem1_BREADY;
reg    grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln95_fu_155_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg = 1'b0;
#0 grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg = 1'b0;
#0 grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg = 1'b0;
#0 grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg = 1'b0;
#0 grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg = 1'b0;
end

conv2d_out_image_x_RAM_AUTO_1R1W #(
    .DataWidth( 11 ),
    .AddressRange( 15876 ),
    .AddressWidth( 14 ))
out_image_x_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(out_image_x_address0),
    .ce0(out_image_x_ce0),
    .we0(out_image_x_we0),
    .d0(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_d0),
    .q0(out_image_x_q0)
);

conv2d_out_image_x_RAM_AUTO_1R1W #(
    .DataWidth( 11 ),
    .AddressRange( 15876 ),
    .AddressWidth( 14 ))
out_image_y_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(out_image_y_address0),
    .ce0(out_image_y_ce0),
    .we0(out_image_y_we0),
    .d0(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_d0),
    .q0(out_image_y_q0)
);

conv2d_out_image_sobel_RAM_AUTO_1R1W #(
    .DataWidth( 13 ),
    .AddressRange( 15876 ),
    .AddressWidth( 14 ))
out_image_sobel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(out_image_sobel_address0),
    .ce0(out_image_sobel_ce0),
    .we0(out_image_sobel_we0),
    .d0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_d0),
    .q0(out_image_sobel_q0)
);

conv2d_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2 grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_ready),
    .m_axi_gmem_AWVALID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .out_image_x_address0(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_address0),
    .out_image_x_ce0(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_ce0),
    .out_image_x_we0(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_we0),
    .out_image_x_d0(grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_d0),
    .in_image(in_image_read_reg_176)
);

conv2d_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6 grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_ready),
    .m_axi_gmem_AWVALID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .out_image_y_address0(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_address0),
    .out_image_y_ce0(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_ce0),
    .out_image_y_we0(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_we0),
    .out_image_y_d0(grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_d0),
    .in_image(in_image_read_reg_176)
);

conv2d_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10 grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_ready),
    .out_image_x_address0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_address0),
    .out_image_x_ce0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_ce0),
    .out_image_x_q0(out_image_x_q0),
    .out_image_y_address0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_address0),
    .out_image_y_ce0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_ce0),
    .out_image_y_q0(out_image_y_q0),
    .out_image_sobel_address0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_address0),
    .out_image_sobel_ce0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_ce0),
    .out_image_sobel_we0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_we0),
    .out_image_sobel_d0(grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_d0)
);

conv2d_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12 grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_ready),
    .out_image_sobel_address0(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_address0),
    .out_image_sobel_ce0(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_ce0),
    .out_image_sobel_q0(out_image_sobel_q0),
    .max_val_2_out(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out),
    .max_val_2_out_ap_vld(grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out_ap_vld)
);

conv2d_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14 grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start),
    .ap_done(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_done),
    .ap_idle(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_idle),
    .ap_ready(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_ready),
    .m_axi_gmem1_AWVALID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(8'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(11'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .out_image(out_image_read_reg_170),
    .out_image_sobel_address0(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_address0),
    .out_image_sobel_ce0(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_ce0),
    .out_image_sobel_q0(out_image_sobel_q0),
    .zext_ln98(max_val_reg_193)
);

conv2d_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_image(in_image),
    .out_image(out_image),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

conv2d_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 8 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_ARVALID),
    .I_CH0_ARREADY(gmem_ARREADY),
    .I_CH0_ARADDR(gmem_ARADDR),
    .I_CH0_ARLEN(gmem_ARLEN),
    .I_CH0_RVALID(gmem_RVALID),
    .I_CH0_RREADY(gmem_RREADY),
    .I_CH0_RDATA(gmem_RDATA),
    .I_CH0_RFIFONUM(gmem_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem_WREADY),
    .I_CH0_WDATA(8'd0),
    .I_CH0_WSTRB(1'd0),
    .I_CH0_BVALID(gmem_BVALID),
    .I_CH0_BREADY(1'b0)
);

conv2d_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 11 ),
    .CH0_USER_DW( 8 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(gmem1_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(gmem1_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(gmem1_RDATA),
    .I_CH0_RFIFONUM(gmem1_RFIFONUM),
    .I_CH0_AWVALID(gmem1_AWVALID),
    .I_CH0_AWREADY(gmem1_AWREADY),
    .I_CH0_AWADDR(gmem1_AWADDR),
    .I_CH0_AWLEN(gmem1_AWLEN),
    .I_CH0_WVALID(gmem1_WVALID),
    .I_CH0_WREADY(gmem1_WREADY),
    .I_CH0_WDATA(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WDATA),
    .I_CH0_WSTRB(grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WSTRB),
    .I_CH0_BVALID(gmem1_BVALID),
    .I_CH0_BREADY(gmem1_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_ready == 1'b1)) begin
            grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_image_read_reg_176 <= in_image;
        out_image_read_reg_170 <= out_image;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        max_val_reg_193 <= max_val_fu_161_p3;
    end
end

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((gmem1_BVALID == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((gmem1_AWREADY == 1'b0) | (grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done == 1'b0))) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem1_AWREADY == 1'b0) | (grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWADDR = out_image_read_reg_170;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWADDR = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWADDR;
    end else begin
        gmem1_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem1_AWREADY == 1'b0) | (grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWLEN = 64'd15876;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWLEN = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWLEN;
    end else begin
        gmem1_AWLEN = 'bx;
    end
end

always @ (*) begin
    if ((~((gmem1_AWREADY == 1'b0) | (grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        gmem1_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_AWVALID = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_AWVALID;
    end else begin
        gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gmem1_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_BREADY = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_BREADY;
    end else begin
        gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        gmem1_WVALID = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_m_axi_gmem1_WVALID;
    end else begin
        gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem1_blk_n_AW = m_axi_gmem1_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem1_blk_n_B = m_axi_gmem1_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARADDR = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARLEN = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARLEN = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARVALID = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_ARVALID = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_RREADY = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state1))) begin
        gmem_RREADY = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_image_sobel_address0 = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_image_sobel_address0 = grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_sobel_address0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_address0;
    end else begin
        out_image_sobel_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        out_image_sobel_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_out_image_sobel_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        out_image_sobel_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_out_image_sobel_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_sobel_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_ce0;
    end else begin
        out_image_sobel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_sobel_we0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_sobel_we0;
    end else begin
        out_image_sobel_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_x_address0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_image_x_address0 = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_address0;
    end else begin
        out_image_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_x_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_image_x_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_ce0;
    end else begin
        out_image_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_image_x_we0 = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_out_image_x_we0;
    end else begin
        out_image_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_y_address0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_image_y_address0 = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_address0;
    end else begin
        out_image_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        out_image_y_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_out_image_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        out_image_y_ce0 = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_ce0;
    end else begin
        out_image_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_image_y_we0 = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_out_image_y_we0;
    end else begin
        out_image_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if ((~((gmem1_AWREADY == 1'b0) | (grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((gmem1_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_39_1_VITIS_LOOP_40_2_fu_106_ap_start_reg;

assign grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_56_5_VITIS_LOOP_57_6_fu_116_ap_start_reg;

assign grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_73_9_VITIS_LOOP_74_10_fu_124_ap_start_reg;

assign grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_ap_start_reg;

assign grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start = grp_conv2d_Pipeline_VITIS_LOOP_98_13_VITIS_LOOP_100_14_fu_137_ap_start_reg;

assign icmp_ln95_fu_155_p2 = ((grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out == 16'd0) ? 1'b1 : 1'b0);

assign max_val_fu_161_p3 = ((icmp_ln95_fu_155_p2[0:0] == 1'b1) ? 16'd1 : grp_conv2d_Pipeline_VITIS_LOOP_85_11_VITIS_LOOP_87_12_fu_131_max_val_2_out);

endmodule //conv2d
